// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteMTP.DataContext;

#nullable disable

namespace TesteMTP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240708234321_Migration1")]
    partial class Migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TesteMTP.Model.TaskModel", b =>
                {
                    b.Property<int>("idTask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTask"));

                    b.Property<DateTime>("dtCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtTask")
                        .HasColumnType("datetime2");

                    b.Property<int>("idStatus")
                        .HasColumnType("int");

                    b.Property<string>("strDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTask");

                    b.ToTable("T_TASK");
                });
#pragma warning restore 612, 618
        }
    }
}
